version: '3.7'

services:
  backend:
    container_name: backend
    image: node:14-alpine
    ports:
      - 8081:8081
    working_dir: /backend
    volumes:
      - ./:/backend
    environment:
      NODE_ENV: prod
    command: sh -c "yarn install --prod && yarn run babel:prod"
    networks:
      - backend_network
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend_network

volumes:
  mongodb:

networks:
  backend_network:
    name: backend_network
