version: '2'

services:
  backend:
    build: backend
    container_name: backend
    ports:
      - 8080:8080
      - 7979:7979
    volumes:
      - ./backend:/var/www/backend
    tty: true
    # change command path in future for inspect
    command: node --inspect=0.0.0.0:7979 src/index.js
    # in future add depends on db for example