version: '3.7'

services:
  backend:
    container_name: backend
    image: node:14-alpine
    ports:
      - 8081:8081
    working_dir: /backend
    volumes:
      - ./:/backend
    environment:
      NODE_ENV: production
    command: sh -c "yarn install --production && yarn run babel:prod"
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network